"""
Core voice pipeline: Deepgram STT → OpenAI LLM → Deepgram TTS.

Joins a LiveKit room, loads project config from Supabase,
and runs the conversational pipeline (livekit-agents 1.x API).
"""

import asyncio
import logging
import time

from typing import Optional

from livekit.agents import Agent, AgentSession, AutoSubscribe, JobContext, function_tool
from livekit.plugins import deepgram, openai, silero
import httpx

from agent.config_loader import load_project_config, resolve_call_by_sid
from agent.transcript_tracker import TranscriptTracker
from agent.billing_reporter import report_call_end

logger = logging.getLogger("ainet-voice")


def _build_agent(instructions: str, voice_tools: list, n8n_url: str | None) -> Agent:
    """
    Create an Agent subclass with dynamically registered n8n tools (if any).
    """
    if not voice_tools:
        return Agent(instructions=instructions)

    # Build tool methods dynamically
    methods: dict = {"__annotations__": {}}

    for tool_def in voice_tools:
        name = tool_def.get("name")
        description = tool_def.get("description", "")
        endpoint = tool_def.get("n8n_endpoint") or n8n_url
        if not name or not endpoint:
            continue

        # Capture loop vars in default args
        async def _tool_fn(self, _name=name, _endpoint=endpoint, _desc=description, **kwargs):
            logger.info(f"Tool call: {_name} with args: {kwargs}")
            try:
                async with httpx.AsyncClient() as client:
                    resp = await client.post(
                        _endpoint,
                        json={"tool": _name, "arguments": kwargs},
                        timeout=10.0,
                    )
                    data = resp.json()
                    return data.get("result", str(data))
            except Exception as e:
                logger.error(f"Tool {_name} failed: {e}")
                return f"Error: {str(e)}"

        _tool_fn.__name__ = name
        _tool_fn.__doc__ = description
        methods[name] = function_tool(_tool_fn)

    DynamicAgent = type("DynamicAgent", (Agent,), methods)
    return DynamicAgent(instructions=instructions)


async def _resolve_ids_from_sip(ctx: JobContext) -> Optional[tuple[str, str]]:
    """
    Find project_id and call_id via the SIP participant's sip.trunkPhoneNumber attribute.
    That attribute holds the SIP URI user part (e.g. v-38017450-b7772f18) which matches
    livekit_room_name in call_logs — set by the Twilio webhook before dialing.
    Works with Individual Dispatch (room name is auto-generated by LiveKit).
    Checks existing participants first, then waits up to 10 s for one to join.
    """
    from agent.config_loader import resolve_room_ids

    def _trunk_phone(participant) -> Optional[str]:
        return participant.attributes.get("sip.trunkPhoneNumber")

    # Check participants already in room
    for p in ctx.room.remote_participants.values():
        trunk_phone = _trunk_phone(p)
        if trunk_phone:
            return await resolve_room_ids(trunk_phone)

    # Wait for SIP participant to arrive
    ready = asyncio.Event()
    holder: dict = {}

    def on_join(participant):
        trunk_phone = _trunk_phone(participant)
        if trunk_phone and not ready.is_set():
            holder["trunk_phone"] = trunk_phone
            ready.set()

    ctx.room.on("participant_connected", on_join)
    try:
        await asyncio.wait_for(ready.wait(), timeout=10.0)
        if holder.get("trunk_phone"):
            return await resolve_room_ids(holder["trunk_phone"])
    except asyncio.TimeoutError:
        logger.error(f"Timeout waiting for SIP participant in room {ctx.room.name}")
    finally:
        ctx.room.off("participant_connected", on_join)
    return None


async def entrypoint(ctx: JobContext):
    await ctx.connect(auto_subscribe=AutoSubscribe.AUDIO_ONLY)

    room_name = ctx.room.name
    logger.info(f"Agent joined room {room_name}")

    resolved = await _resolve_ids_from_sip(ctx)
    if not resolved:
        logger.error(f"Could not resolve project/call for room {room_name}")
        return
    project_id, call_id = resolved
    logger.info(f"Room {room_name} | project={project_id} call={call_id}")

    config = await load_project_config(project_id)
    if not config:
        logger.error(f"No voice config found for project {project_id}")
        return

    # Model names are stored with "deepgram-" prefix in DB — strip it for plugins
    stt_model = config.get("stt_model", "deepgram-nova-2").replace("deepgram-", "")
    tts_model = config.get("tts_model", "deepgram-aura-2-asteria-en").replace("deepgram-", "")
    stt_language = config.get("stt_language", "es")
    llm_model = config.get("voice_ai_model", "gpt-4o-mini")
    system_prompt = config.get("voice_system_prompt") or "Eres un asistente de voz útil."
    greeting = config.get("greeting_message", "Hola, ¿en qué le puedo ayudar?")
    voice_tools = config.get("voice_tools") or []
    n8n_url = config.get("n8n_voice_webhook_url")

    tracker = TranscriptTracker(project_id=project_id, call_id=call_id)
    start_time = time.time()

    agent = _build_agent(system_prompt, voice_tools, n8n_url)

    session = AgentSession(
        stt=deepgram.STT(model=stt_model, language=stt_language),
        llm=openai.LLM(model=llm_model),
        tts=deepgram.TTS(model=tts_model),
        vad=silero.VAD.load(),
    )

    @session.on("user_speech_committed")
    def on_user_speech(ev):
        text = getattr(ev, "transcript", None) or str(ev)
        tracker.add_entry("user", text)

    @session.on("agent_speech_committed")
    def on_agent_speech(ev):
        text = getattr(ev, "transcript", None) or str(ev)
        tracker.add_entry("assistant", text)

    await session.start(agent=agent, room=ctx.room)

    first_message_mode = config.get("first_message_mode", "assistant-speaks-first")
    if first_message_mode == "assistant-speaks-first":
        await session.say(greeting)
        tracker.add_entry("assistant", greeting)

    @ctx.room.on("participant_disconnected")
    def on_disconnect(participant):
        if ctx.room.remote_participants:
            return
        duration = int(time.time() - start_time)
        logger.info(f"Call ended. Duration: {duration}s")
        analysis_config = {
            "analysis_summary_prompt": config.get("analysis_summary_prompt"),
            "analysis_structured_schema": config.get("analysis_structured_schema"),
            "analysis_success_prompt": config.get("analysis_success_prompt"),
            "voice_ai_model": llm_model,
        }
        asyncio.create_task(report_call_end(
            call_id=call_id,
            project_id=project_id,
            duration_seconds=duration,
            tracker=tracker,
            analysis_config=analysis_config,
        ))
